ac_tickers = ["KMD", "REVS", "SUPERNET", "DEX",
              "PANGEA", "JUMBLR", "BET",
              "CRYPTO", "HODL", "MSHARK",
              "BOTS", "MGW", "COQUICASH", 
              "KV", "MESH", "AXO", "ETOMIC",
              "BTCH", "NINJA", "OOT", "ZILLA",
              "RFOX", "SEC", "CCL", "PIRATE",
              "PGT", "KSB", "OUR", "ILN",
              "RICK", "MORTY", "KOIN",
              "ZEXO", "K64", "THC", "WLC21"]